<a href="https://colab.research.google.com/github/AMIT110409/Deep_learning_Algo_implementation/blob/main/backpropagation_regression%26classifcation_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#3 here we solve regression problem .

import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [16]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):

      parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
      parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters

In [17]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [18]:
def linear_forward(A_prev,W,b): ## whatever input we got for a node as a input we are doing dot product of w and a
  Z = np.dot(W.T,A_prev)+b
  return Z


In [30]:
# forward propagation
def L_layer_forward(X,parameters):

  A = X
  L = len(parameters) // 2  # number of layer in neural network

  for l in range(1,L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b'+ str(l)]
    print("A"+str(l-1)+": " ,A)
    print("W"+str(l)+": ",Wl)
    print("b"+str(l)+": ",bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl,bl)
    print("A"+str(l)+": ",A)
    print("**"*20)

  return A,A_prev

In [31]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)  # shape(no. of features, no. of training example)
y = df[['lpa']].values[0][0]

# parameter initialization
parameters = initialize_parameters([2,2,1])

L_layer_forward(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [32]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001*2*(y- y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001*2*(y- y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001*2*(y- y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001*2*(y- y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001*2*(y- y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001*2*(y- y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001*2*(y- y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001*2*(y- y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001*2*(y- y_hat)*parameters['W2'][1][0])


In [33]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)  # shape(no. of features, no. of training example)
y = df[['lpa']].values[0][0]

# parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat , A1 = L_layer_forward(X,parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [34]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)  # shape(no. of features, no. of training example)
y = df[['lpa']].values[0][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('parameters after the update')
print(parameters)



A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
parameters after the update
{'W1': array([[0.10658137, 0.10658137],
       [0.10658137, 0.10658137]]), 'b1': array([[0.00082267],
       [0.00082267]]), 'W2': array([[0.111776],
       [0.111776]]), 'b2': array([[0.00736]])}


In [35]:
# epoch implementation
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
  Loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa','profile_score']].values[j].reshape(2,1)  # shape(no. of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # paramter initialization

    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append((y-y_hat)**2)
  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.00736]]
----------------------------------------
A2:  [[0.38876757]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11481311 0.11716504]
 [0.11481311 0.11716504]]
b1:  [[0.00199863]
 [0.00199863]]
----------------------------------------
A1:  [[1.83900839]
 [1.8766392 ]]
****************************************
A1:  [[1.83900839]
 [1.8766392 ]]
W2:  [[0.12751067]
 [0.12

{'W1': array([[0.273603  , 0.3993222 ],
        [0.28787155, 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893],
        [0.50219328]]),
 'b2': array([[0.11841278]])}

In [36]:
A1

array([[4.71178104],
       [6.80512062]])

**Implement with the help of keras . **

In [1]:
# here also we  solve regression problem  with the help of keras .
import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df


cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))  #3 hidden layer
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()    ## keras gives us random weights .

[array([[-0.9615881 , -0.24660617],
        [ 0.52393496, -0.65138304]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.7943703 ],
        [-0.16302168]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 31.2627  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.1444 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.3568 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30.7696 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.2025 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.8398 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.0970 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.2327 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.4086 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.2945 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19.4600 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 27.4469 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.4710 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.9927 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.1241 
Epoch 16/75
4/4 ━━

In [14]:
model.get_weights()

[array([[0.37362298, 0.37362298],
        [0.36554193, 0.36554193]], dtype=float32),
 array([0.2722692, 0.2722692], dtype=float32),
 array([[0.37287772],
        [0.37287772]], dtype=float32),
 array([0.20468347], dtype=float32)]

In [16]:
## here we solve classification problem .

import numpy as np
import pandas as pd


In [17]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])

In [18]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [19]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for  l in range(1,L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))


  return parameters

In [20]:
# utility functions
def sigmoid(Z):
  A = 1/(1+np.exp(-Z))
  return A

In [21]:
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T,A_prev)+b
  A = sigmoid(Z)
  return A

In [22]:
# forward propagation
def L_layer_forward(X,parameters):

  A = X
  L = len(parameters) // 2  # number of layer in neural network

  for l in range(1,L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b'+ str(l)]
    print("A"+str(l-1)+": " ,A)
    print("W"+str(l)+": ",Wl)
    print("b"+str(l)+": ",bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl,bl)
    print("A"+str(l)+": ",A)
    print("**"*20)

  return A,A_prev

In [23]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001*(y- y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001*(y- y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001*(y- y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001*(y- y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001*(y- y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001*(y- y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001*(y- y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001*(y- y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001*(y- y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))


In [24]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1) #Shape(no. of features,no. of training example)
y = df[['placed']].values[0][0]

# parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
Loss for this student -  0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [26]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1) #Shape(no. of features,no. of training example)
y = df[['placed']].values[0][0]

# parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)
print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

A0:  [[7]
 [9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
Loss for this student -  0.613402628898913


{'W1': array([[0.10000449, 0.10000577],
        [0.10000449, 0.10000577]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [28]:
# epochs implementation
parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
  Loss = []

  for  j in range(df.shape[0]):
    X = df[['cgpa','profile_score']].values[J].reshape(2,1) #Shape(no. of features,no. of training example)
    y = df[['placed']].values[j][0]

    # parameter initialization
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)
    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))
  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters


parameters


A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[0.83201839]
 [0.83201839]]
****************************************
A1:  [[0.83201839]
 [0.83201839]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.54150519]]
****************************************
A0:  [[8]
 [8]]
W1:  [[0.10000513 0.10000513]
 [0.10000513 0.10000513]]
b1:  [[6.41054186e-07]
 [6.41054186e-07]]
----------------------------------------
A1:  [[0.83202994]
 [0.83202994]]
****************************************
A1:  [[0.83202994]
 [0.83202994]]
W2:  [[0.10003815]
 [0.10003815]]
b2:  [[0.100084]]
----------------------------------------
A2:  [[0.56624659]]
****************************************
A0:  [[8]
 [8]]
W1:  [[0.10000998 0.10000998]
 [0.10000998 0.10000998]]
b1:  [[1.24770113e-06]
 [1.24770113e-06]]
----------------------------------------
A1:  [[0.83204088]
 [0.83204088]]
****************************************
A1:  [

{'W1': array([[0.09998551, 0.09998551],
        [0.09998551, 0.09998551]]),
 'b1': array([[-1.81178944e-06],
        [-1.81178944e-06]]),
 'W2': array([[0.09989189],
        [0.09989189]]),
 'b2': array([[0.09983527]])}